version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/chatapp
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
